// Generates public/assets/config.js from the environment so the static bundles
// know where the Railway backend lives. Runs automatically before `dev` and
// `build` (see package.json), so setting NEXT_PUBLIC_API_BASE_URL in the
// Cloudflare Pages project is enough to repoint the whole frontend at a
// different backend — no code change, no rebuild of the bundles themselves.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const DEFAULT_API_BASE_URL = 'https://dalivim-escrow-production.up.railway.app';

const apiBaseUrl = (
  process.env.NEXT_PUBLIC_API_BASE_URL || DEFAULT_API_BASE_URL
).replace(/\/+$/, '');

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '..', 'public', 'assets', 'config.js');

const banner = '// AUTO-GENERATED by scripts/gen-config.mjs — do not edit by hand.';
const body = `${banner}
// Runtime config consumed by the in-iframe bundles (see public/src/api.js).
window.DALIVIM_API_BASE_URL = ${JSON.stringify(apiBaseUrl)};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
console.log(`[gen-config] API base URL -> ${apiBaseUrl}`);
